### ISSUE TITLE
Not able to run on iOS simulator

### ISSUE THREAD

**Issue by breahna-ebs** [klarna/react-native-klarna-inapp-sdk#2] opened 2019-09-13 14:38 UTC
I'm not able to run the app on iOS simulator any more but it's seems to be working fine on physical device. 
`
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: .../Frameworks/KlarnaMobileSDK.framework/KlarnaMobileSDK
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftCore.dylib: mach-o, but not built for iOS simulator
`

What should I do to make it run on simulator?

**Comment by omarbh** [comment] 2019-09-23 09:06
Thanks for reporting this @breahna-ebs , we will look into it getting back as soon as possible

**Comment by omarbh** [comment] 2020-03-02 10:03
Hi @breahna-ebs this is should be fixed, please use the latest version and get back to us if the issue is still persisting

**Comment by omarbh** [comment] 2020-05-15 08:59
Hi @breahna-ebs I will closed this ticket as the issue has been fixed in the latest release and we also update the read me file for information on how to fix the issue

**Closed by omarbh** 2020-05-15 08:59 UTC
Labels: in progress, investigation
