### ISSUE TITLE
'KlarnaMobileSDK/KlarnaMobileSDK-Swift.h' file not found

### ISSUE THREAD

**Issue by harriot** [klarna/react-native-klarna-inapp-sdk#5] opened 2019-10-10 16:19 UTC
- Settings

pod 'KlarnaMobileSDK'
 "react-native-klarna-inapp-sdk": "^1.0.3"
Libraries and binary linked
After a fresh` npm i `and pod install with `react-native link.` 

Getting `/source/app/node_modules/react-native-klarna-inapp-sdk/ios/view/PaymentViewWrapper.m:10:9: 'KlarnaMobileSDK/KlarnaMobileSDK-Swift.h' file not found`

![Screenshot 2019-10-10 at 17 08 47](https://user-images.githubusercontent.com/5880750/66586534-ab12fb80-eb80-11e9-9c6d-1ca53c832f97.png)
![Screenshot 2019-10-10 at 17 09 37](https://user-images.githubusercontent.com/5880750/66586578-c1b95280-eb80-11e9-933b-5f0282bc212d.png)

**Comment by omarbh** [comment] 2020-03-02 09:50
Hi @harriot 
This should be fixed in the latest version, please update and tell us if the issue is fixed on your side.

**Closed** 2020-03-31 10:43 UTC
Labels: in progress, investigation
